### ISSUE TITLE
Minimum phase version

### ISSUE THREAD

**Issue by micsthepick** [Nbickford/REAPERDenoiser#7]
Pre-ringing or pre-echoes happen a little too much sometimes, plus the delay can be unacceptable.

I've tried to implement a minimum phase filter, this should help to reduce delay, and also cut down on the artifacts.
so far, I have a working denoiser, but I have not yet tried to reduce boundary change related artifacts, nor implement partitioned convolution, but it seems to sound nice, even when clapping with lots of noise.

As discussed earlier, we can split this project out into a more professional version, and a simple educational version that works with your linked blog post, but I thought it would be a good idea to show you what I've made, and see how you think it sounds.

I was wondering if you'd like me to maintain the professional version separately in my fork?, and also wanted to keep you posted on the updates that I've made.

**Comment by micsthepick** [comment]
here is the references I used to create the minimum phase filter:

https://www.katjaas.nl/minimumphase/minimumphase.html
https://dspguru.com/dsp/howtos/how-to-design-minimum-phase-fir-filters/ - specifically the spectral factorization technique

other methods to look into could include zero padding the initial FIR which is extracted from the attenuationFactor spectral coefficients after applying the IFFT.

**Comment by ghost** [comment]
Absolutely - I could rename this repository to something like `REAPERDenoiserTutorial` and point to your professional version, if that sounds good to you!

**Comment by micsthepick** [comment]
sure thing!
